"""
Django settings for crypto_track project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

from crypto_track.env import env, env_bool, env_int, env_list

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Fail-closed: DEBUG is False unless the environment EXPLICITLY opts in via a
# valid boolean. Unset -> False (production). A malformed value (e.g. "prod",
# "Production") raises ImproperlyConfigured instead of silently enabling DEBUG.
DEBUG = env_bool("DJANGO_DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
if DEBUG:
    # Zero-config fallback for development/test/CI only. Obviously insecure and
    # unreachable when DEBUG is off, where SECRET_KEY is required.
    SECRET_KEY = env("SECRET_KEY", default="dev-insecure-do-not-use-in-production")
else:
    SECRET_KEY = env("SECRET_KEY")  # required in production

if DEBUG:
    ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])
else:
    ALLOWED_HOSTS = env_list("ALLOWED_HOSTS")  # required in production
    if "*" in ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "ALLOWED_HOSTS must not contain '*' when DEBUG is off; "
            "list the explicit hostnames this app serves."
        )
if DEBUG:
    # Zero-config default for development/test/CI. Django requires each origin
    # to include a scheme; these cover runserver's default host:port.
    CSRF_TRUSTED_ORIGINS = env_list(
        "CSRF_TRUSTED_ORIGINS",
        default=["http://localhost:8000", "http://127.0.0.1:8000"],
    )
else:
    CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")  # required in production
    missing_scheme = [origin for origin in CSRF_TRUSTED_ORIGINS if "://" not in origin]
    if missing_scheme:
        raise ImproperlyConfigured(
            "CSRF_TRUSTED_ORIGINS entries must include a scheme "
            f"(e.g. 'https://example.com'); got {missing_scheme}."
        )


# Production security hardening
# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
#
# All of the following are inert in development (DEBUG on) and active only when
# DEBUG is off. Deploy target is Railway/PaaS: TLS terminates at the platform
# edge and requests reach this process over plaintext HTTP with the original
# scheme in X-Forwarded-Proto (see SECURE_PROXY_SSL_HEADER below).
if not DEBUG:
    # --- HTTPS enforcement -------------------------------------------------
    # Redirect all HTTP requests to HTTPS. Env-overridable as an incident
    # kill-switch (e.g. to break a redirect loop while debugging proxy config).
    #
    # Step 16 (health checks): a platform health check that hits the app over
    # internal HTTP without an "X-Forwarded-Proto: https" header will receive a
    # 301 to HTTPS and may be marked unhealthy. Mitigate there by exempting the
    # health path (e.g. SECURE_REDIRECT_EXEMPT = [r"^healthz$"]) or pointing the
    # health check at the public HTTPS domain.
    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=True)

    # Only transmit session/CSRF cookies over HTTPS. Production is HTTPS-only,
    # so there is no legitimate reason to expose these over plaintext.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # --- HSTS (HTTP Strict Transport Security) -----------------------------
    # HSTS instructs browsers to refuse plaintext HTTP for this host for
    # max-age seconds. It is a hard-to-reverse commitment: if HTTPS later
    # breaks, clients that already cached the header are locked out until it
    # expires. Start conservative (1 hour) and ramp the max-age up via env once
    # the HTTPS setup is proven (target: 31536000 / 1 year). Subdomains and
    # preload stay OFF until explicitly opted into.
    SECURE_HSTS_SECONDS = env_int("SECURE_HSTS_SECONDS", default=3600)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
        "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False
    )
    SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", default=False)

    # --- Proxy TLS termination ---------------------------------------------
    # When a TLS-terminating proxy/router (Railway, Heroku, most PaaS/LBs)
    # forwards requests to the app over plaintext HTTP, Django only learns the
    # original scheme from X-Forwarded-Proto. Enable ONLY when such a proxy
    # exists AND it overwrites any client-supplied X-Forwarded-Proto (otherwise
    # the header is spoofable -> a client could forge "https" -> security risk).
    # Conversely, if this is omitted while behind a TLS-terminating proxy, every
    # request looks like plaintext to Django and SECURE_SSL_REDIRECT loops
    # forever (301 -> 301 -> ...). On Railway, set TRUST_PROXY_SSL_HEADER=true.
    if env_bool("TRUST_PROXY_SSL_HEADER", default=False):
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "common.apps.CommonConfig",
    "coins.apps.CoinsConfig",
    "accounts.apps.AccountsConfig",
    "portfolio.apps.PortfolioConfig",
    "crispy_forms",
    "crispy_bootstrap5",
    "django_apscheduler",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serves static files directly from the app process (compressed +
    # hashed). Must sit immediately after SecurityMiddleware.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "crypto_track.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "crypto_track.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=env("DATABASE_URI", default="postgres://crypto_track@/crypto_track"),
    )
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "cache",
    }
}

CACHE_SUPPORTED_COINS_TIMEOUT_SECONDS = 3600 * 2  # 2 hours
CACHE_MARKET_PAGE_TIMEOUT_SECONDS = 60


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Authentication redirects
# https://docs.djangoproject.com/en/5.2/ref/settings/#login-url
# Stated explicitly so auth redirects don't depend on Django's defaults
# (which assume accounts are mounted at /accounts/ and land logins on the
# nonexistent /accounts/profile/). Named URLs survive changes to URL prefixes.

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
#
# Strategy: this app has a small, hand-maintained set of static assets (the
# project's `style.css` plus Django admin's bundled files). We serve them from
# the app process itself via WhiteNoise rather than a separate CDN/reverse proxy.
# - Dev: `runserver` serves from STATICFILES_DIRS (and app dirs) via the
#   staticfiles finders; no collectstatic needed.
# - Prod: run `manage.py collectstatic` into STATIC_ROOT; WhiteNoise serves those
#   files, compressed and content-hashed for far-future caching.
STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

COINGECKO_ENDPOINT = "https://api.coingecko.com/api/v3/"
# Read lazily so that settings import (and `manage.py check`, migrations, etc.)
# does not fail when the key is absent. It is only required at runtime for
# actual CoinGecko requests (see coins/services.py).
COINGECKO_KEY = env("COINGECKO_KEY", default="")
