# Generated by Django 5.2.5 on 2025-10-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
