# Generated by Django 5.2.5 on 2026-07-06 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0002_coin_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
