# Generated by Django 5.2.5 on 2025-09-27 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portfoliotransaction",
            old_name="transaction_type",
            new_name="type",
        ),
    ]
