# Generated by Django 5.2.5 on 2026-07-06 01:26

from decimal import Decimal

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0002_coin_is_active"),
        ("portfolio", "0002_rename_transaction_type_portfoliotransaction_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliotransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("1E-8"))],
            ),
        ),
        migrations.AlterField(
            model_name="portfoliotransaction",
            name="price",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("1E-8"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliotransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="portfolio_transaction_amount_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliotransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)),
                name="portfolio_transaction_price_gt_0",
            ),
        ),
    ]
