# Generated by Django 5.2.5 on 2026-07-06 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0002_coin_is_active"),
        ("portfolio", "0004_portfoliotransaction_trade_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="portfoliotransaction",
            index=models.Index(
                fields=["user", "coin", "created"], name="pf_txn_user_coin_created"
            ),
        ),
        migrations.AddIndex(
            model_name="portfoliotransaction",
            index=models.Index(
                fields=["user", "trade_date"], name="pf_txn_user_trade_date"
            ),
        ),
    ]
