# Generated by Django 5.2 on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_portfoliotransaction_pf_txn_user_coin_created_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="portfoliotransaction",
            name="pf_txn_user_coin_created",
        ),
        migrations.AddIndex(
            model_name="portfoliotransaction",
            index=models.Index(
                fields=["user", "coin", "trade_date", "id"],
                name="pf_txn_user_coin_trade_date_id",
            ),
        ),
    ]
